import os
from langchain_core.messages import HumanMessage, AIMessage
from agent.app.core.assistant.assistant import AssistantBase
from agent.app.core.tools.asteroid_tools import (
    get_space_weather_events,
    search_scientific_knowledge,
    WEATHER_TOOLS,
    KNOWLEDGE_TOOLS,
)


def test_raw_tools():
    print("\n" + "=" * 50)
    print("STEP 1: TESTING RAW TOOL FUNCTIONALITY")
    print("=" * 50)

    # Test 1: Test the SQL-backed Space Weather tool
    print("[+] Testing get_space_weather_events (SQL layer)...")
    weather_output = get_space_weather_events.invoke({"event_type": "CME", "limit": 2})
    print(f"Tool Output:\n{weather_output}\n")

    # Test 2: Test the Vector-backed Knowledge tool
    print("[+] Testing search_scientific_knowledge (Vector layer)...")
    knowledge_output = search_scientific_knowledge.invoke(
        {"query": "black holes and telescopes", "limit": 1}
    )
    print(f"Tool Output:\n{knowledge_output}\n")


def test_assistant_llm():
    print("=" * 50)
    print("STEP 2: TESTING ASSISTANT BASE & TOOL BINDING")
    print("=" * 50)

    # Verify Ollama or Groq is targeted based on environment variables
    env = os.getenv("ENVIRONMENT", "local")
    print(f"[+] Initializing Assistant in [{env}] mode...")

    system_prompt = (
        "You are an expert Space Weather monitoring agent. "
        "You must use your tools to look up live events before answering questions."
    )

    # Instantiate the assistant base with our weather tools bound to it
    assistant = AssistantBase(system_prompt=system_prompt, tools=WEATHER_TOOLS)

    # Simulate the GraphState working memory structure LangGraph uses
    mock_state = {
        "messages": [
            HumanMessage(
                content="Are there any recent Coronal Mass Ejections (CMEs) reported?"
            )
        ]
    }

    try:
        print(
            "[+] Sending query to LLM. Checking for autonomous tool invocation decision..."
        )
        result = assistant(mock_state)

        # Extract the returned AI message
        ai_message = result["messages"][0]

        print("\n[✓] LLM Response Received Successfully!")
        print(f"AI Message Content: '{ai_message.content}'")

        # Check if the model correctly decided it needed to call a tool
        if ai_message.tool_calls:
            print("\n[✓] SUCCESS: The LLM autonomously chose to use a tool!")
            for tool_call in ai_message.tool_calls:
                print(f"    -> Tool to call: {tool_call['name']}")
                print(f"    -> Arguments generated by LLM: {tool_call['args']}")
        else:
            print(
                "\n[-] NOTICE: The LLM responded with raw text instead of a tool call."
            )
            print(
                "    If using Ollama, ensure your local model (like qwen2.5:7b) supports function calling."
            )

    except Exception as e:
        print(f"\n[X] Error during LLM invocation: {e}")
        print(
            "    Ensure your local Ollama instance is running (`ollama run qwen2.5:7b`) or GROQ_API_KEY is configured."
        )


if __name__ == "__main__":
    # Run both testing phases
    test_raw_tools()
    test_assistant_llm()
